### ISSUE TITLE
Difference in rendering issues with celiagg

### ISSUE THREAD

**Issue by jdeschenes** [celiagg/celiagg#43]
Hello,

I thinkit has already been mentionned in enthought/enable#247, but the text rendering of a chaco plot between the agg and celiagg backend is different. To me, it looks better on the original agg backend. For reference, this is the bigdata example on chaco.

![celiagg](https://user-images.githubusercontent.com/9948816/28496042-a213ce0e-6f2e-11e7-8f01-5e27961a2de6.png)

![agg](https://user-images.githubusercontent.com/9948816/28496043-a68b009c-6f2e-11e7-8522-f2a3cffc8a39.png)

The text seems blurry on celiagg and there is a black edge on the graph. You mentionned that it was an easy fix... Can you elaborate a bit on how that's done?

The noninteractive.py example is different in that the background outside of the graph area is transparent as opposed to being white on the original agg backend.

**Comment by jwiggins** [comment]
This looks like an anti-aliasing problem in general.

I would look at https://github.com/enthought/enable/blob/master/kiva/celiagg.py#L207-L210 (which uses the `canvas_state.anti_aliased` variable. Try keeping it false and see it that sharpens things up a bit. It's possible that the gamma curve (IIRC) for anti-aliased drawing is just too aggressive in celiagg.

For the dark edge on the plot, I'm not sure. It looks like #32 didn't completely solve the problem.

**Comment by jwiggins** [comment]
I've come back to this to take a closer look. The problem is that this particular chaco example uses double buffering (https://github.com/enthought/chaco/blob/4.7.2/examples/demo/bigdata.py#L38). This means that it first renders to an image, and then draws that image. So there is likely a bug somewhere in the image rendering. Possibly because of a the image interpolation which is being used.
